name: CI

# 在推送和 PR 时触发
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  # 代码质量检查和构建测试
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

    - name: Install dependencies
      run: npm ci
      
    - name: Type check
      run: npx vue-tsc --noEmit || echo "Type check warnings found, but continuing..."
      
    - name: Build project
      run: npm run build:no-check
      
    - name: Check build output
      run: |
        echo "Build completed successfully!"
        ls -la dist/
        echo "Build size:"
        du -sh dist/
        
    # 缓存构建产物（仅在主要版本）
    - name: Cache build artifacts
      if: matrix.node-version == '20'
      uses: actions/cache@v4
      with:
        path: dist
        key: build-${{ github.sha }}
        restore-keys: |
          build-
