name: Release

# 当创建 release 或推送 tag 时触发
on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build for production
      run: npm run build:no-check
      env:
        NODE_ENV: production
        
    - name: Create release archive
      run: |
        cd dist
        tar -czf ../sitecopy-${{ github.ref_name }}.tar.gz .
        zip -r ../sitecopy-${{ github.ref_name }}.zip .
        cd ..
        
    - name: Generate build info
      run: |
        echo "# Build Information" > BUILD_INFO.md
        echo "- **Version**: ${{ github.ref_name }}" >> BUILD_INFO.md
        echo "- **Commit**: ${{ github.sha }}" >> BUILD_INFO.md
        echo "- **Build Date**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> BUILD_INFO.md
        echo "- **Node Version**: $(node --version)" >> BUILD_INFO.md
        echo "- **NPM Version**: $(npm --version)" >> BUILD_INFO.md
        echo "" >> BUILD_INFO.md
        echo "## Build Size" >> BUILD_INFO.md
        echo "\`\`\`" >> BUILD_INFO.md
        du -sh dist/ >> BUILD_INFO.md
        echo "\`\`\`" >> BUILD_INFO.md
        
    - name: Upload release assets
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          sitecopy-${{ github.ref_name }}.tar.gz
          sitecopy-${{ github.ref_name }}.zip
          BUILD_INFO.md
        body_path: BUILD_INFO.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create release (for tags)
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          sitecopy-${{ github.ref_name }}.tar.gz
          sitecopy-${{ github.ref_name }}.zip
          BUILD_INFO.md
        body_path: BUILD_INFO.md
        generate_release_notes: true
        draft: false
        prerelease: ${{ contains(github.ref_name, '-') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
